"""
Searcher — Semantic Search Engine (Project 8).

Online (query-time) component:
  1. Encode query with the same SentenceTransformer used during indexing.
  2. Search the FAISS index for top-k candidates.
  3. Optionally re-rank with a cross-encoder for higher precision.
  4. Return ranked SearchResult objects with highlighted snippets.

"Did you mean?" suggestions are generated by spell-correcting the query
using a simple edit-distance approach against a vocabulary built from
the indexed passages.

Usage:
    searcher = Searcher(config)
    searcher.load()
    response = searcher.search("what is machine learning", top_k=10)
"""

import os
import re
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import faiss
import numpy as np
from sentence_transformers import CrossEncoder, SentenceTransformer

from src.config.configuration import Config
from src.utils.common import ensure_dir, setup_logger

logger = setup_logger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class SearchResult:
    """A single ranked search result with optional snippet highlighting."""

    rank: int
    passage_id: int
    passage: str
    score: float
    snippet: str = ""          # highlighted snippet (query terms bolded)
    source: str = "MS MARCO"   # provenance label

    def to_dict(self) -> Dict:
        return {
            "rank": self.rank,
            "passage_id": self.passage_id,
            "passage": self.passage,
            "score": round(self.score, 6),
            "snippet": self.snippet,
            "source": self.source,
        }


@dataclass
class SearchResponse:
    """Complete response returned to the API / Streamlit UI."""

    query: str
    results: List[SearchResult] = field(default_factory=list)
    latency_ms: float = 0.0
    total_indexed: int = 0
    did_you_mean: Optional[str] = None    # spell-corrected suggestion

    def to_dict(self) -> Dict:
        d = {
            "query": self.query,
            "results": [r.to_dict() for r in self.results],
            "latency_ms": round(self.latency_ms, 2),
            "total_indexed": self.total_indexed,
            "num_results": len(self.results),
        }
        if self.did_you_mean:
            d["did_you_mean"] = self.did_you_mean
        return d


# ─────────────────────────────────────────────────────────────────────────────
# Snippet highlighting
# ─────────────────────────────────────────────────────────────────────────────


def _highlight_snippet(
    passage: str,
    query: str,
    window: int = 200,
    marker_open: str = "**",
    marker_close: str = "**",
) -> str:
    """
    Extract a short window from the passage centred on the first query token
    match and wrap matching tokens in markdown bold markers.

    Returns the raw passage if no match is found.
    """
    tokens = re.split(r"\s+", query.strip().lower())
    passage_lower = passage.lower()

    # Find earliest match position
    best_pos = len(passage)
    for tok in tokens:
        idx = passage_lower.find(tok)
        if idx != -1 and idx < best_pos:
            best_pos = idx

    if best_pos == len(passage):
        # No match — return truncated passage
        return passage[:window].rstrip() + ("…" if len(passage) > window else "")

    # Expand window around best_pos
    start = max(0, best_pos - window // 2)
    end = min(len(passage), start + window)
    snippet = passage[start:end]

    # Bold matching tokens (case-insensitive)
    for tok in tokens:
        if len(tok) < 2:
            continue
        pattern = re.compile(re.escape(tok), re.IGNORECASE)
        snippet = pattern.sub(lambda m: f"{marker_open}{m.group()}{marker_close}", snippet)

    prefix = "…" if start > 0 else ""
    suffix = "…" if end < len(passage) else ""
    return prefix + snippet.strip() + suffix


# ─────────────────────────────────────────────────────────────────────────────
# "Did you mean?" — lightweight edit-distance spell checker
# ─────────────────────────────────────────────────────────────────────────────


def _edit_distance(a: str, b: str) -> int:
    """Compute Levenshtein edit distance between two strings."""
    if len(a) < len(b):
        a, b = b, a
    if len(b) == 0:
        return len(a)
    prev = list(range(len(b) + 1))
    for ch_a in a:
        curr = [prev[0] + 1]
        for j, ch_b in enumerate(b):
            cost = 0 if ch_a == ch_b else 1
            curr.append(min(curr[j] + 1, prev[j + 1] + 1, prev[j] + cost))
        prev = curr
    return prev[-1]


class SpellChecker:
    """
    Minimal vocabulary-based spell checker.
    Suggests the closest word from the corpus vocabulary for each OOV token.
    """

    def __init__(self, max_vocab: int = 50_000):
        self._vocab: Dict[str, int] = {}   # word → frequency
        self.max_vocab = max_vocab

    def build_from_passages(self, passages: List[str]) -> None:
        """Build a word-frequency vocabulary from the passage corpus."""
        for passage in passages:
            for word in re.split(r"\W+", passage.lower()):
                if 2 <= len(word) <= 20:
                    self._vocab[word] = self._vocab.get(word, 0) + 1
        # Keep top-N by frequency to bound memory
        if len(self._vocab) > self.max_vocab:
            top = sorted(self._vocab.items(), key=lambda x: -x[1])[: self.max_vocab]
            self._vocab = dict(top)
        logger.info("SpellChecker vocabulary built: %d words.", len(self._vocab))

    def suggest(self, query: str, max_edit_dist: int = 1) -> Optional[str]:
        """
        Return a corrected version of the query if any token looks misspelled.
        Only suggests corrections for tokens with edit distance ≤ max_edit_dist
        to a vocab word that is more frequent.
        """
        if not self._vocab:
            return None

        tokens = query.lower().split()
        corrected = []
        changed = False

        for tok in tokens:
            if tok in self._vocab:
                corrected.append(tok)
                continue

            # Find closest vocab word within max_edit_dist
            best_word, best_dist = tok, max_edit_dist + 1
            for vocab_word in self._vocab:
                if abs(len(vocab_word) - len(tok)) > max_edit_dist:
                    continue
                d = _edit_distance(tok, vocab_word)
                if d < best_dist:
                    best_dist = d
                    best_word = vocab_word

            if best_dist <= max_edit_dist and best_word != tok:
                corrected.append(best_word)
                changed = True
            else:
                corrected.append(tok)

        return " ".join(corrected) if changed else None


# ─────────────────────────────────────────────────────────────────────────────
# Cross-encoder re-ranker
# ─────────────────────────────────────────────────────────────────────────────


class CrossEncoderReranker:
    """
    Re-rank a list of (query, passage) pairs using a cross-encoder model.
    The cross-encoder sees the full query + passage jointly and produces a
    relevance score more accurate than the bi-encoder cosine similarity.

    Default model: cross-encoder/ms-marco-MiniLM-L-6-v2 (~66 MB, fast).
    """

    DEFAULT_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

    def __init__(self, model_name: Optional[str] = None):
        self.model_name = model_name or self.DEFAULT_MODEL
        self._model: Optional[CrossEncoder] = None

    @property
    def model(self) -> CrossEncoder:
        if self._model is None:
            logger.info("Loading cross-encoder: '%s' ...", self.model_name)
            self._model = CrossEncoder(self.model_name, max_length=512)
            logger.info("Cross-encoder loaded.")
        return self._model

    def rerank(
        self,
        query: str,
        results: List[SearchResult],
    ) -> List[SearchResult]:
        """
        Re-score and re-rank results using the cross-encoder.

        Returns a new list sorted by cross-encoder score (descending),
        with rank fields updated.
        """
        if not results:
            return results

        pairs = [[query, r.passage] for r in results]
        scores = self.model.predict(pairs)

        reranked = sorted(
            zip(scores, results), key=lambda x: x[0], reverse=True
        )

        output = []
        for new_rank, (score, result) in enumerate(reranked, start=1):
            output.append(
                SearchResult(
                    rank=new_rank,
                    passage_id=result.passage_id,
                    passage=result.passage,
                    score=float(score),
                    snippet=result.snippet,
                    source=result.source,
                )
            )
        return output


# ─────────────────────────────────────────────────────────────────────────────
# Searcher
# ─────────────────────────────────────────────────────────────────────────────


class Searcher:
    """
    Query-time semantic search component.

    Workflow:
        load()      — Load FAISS index, passage map, and models.
        search(q)   — Encode query → FAISS top-k → optional cross-encoder rerank
                      → highlighted snippets → "Did you mean?" suggestion.

    The class is designed to be instantiated once (e.g., at FastAPI startup)
    and reused for every query.
    """

    def __init__(
        self,
        config: Optional[Config] = None,
        use_reranker: bool = True,
        reranker_model: Optional[str] = None,
        bi_encoder_model: Optional[str] = None,
    ):
        self.config = config or Config()
        self.use_reranker = use_reranker
        self._bi_encoder: Optional[SentenceTransformer] = None
        self._reranker: Optional[CrossEncoderReranker] = None
        self._index: Optional[faiss.Index] = None
        self._passage_map: Optional[Dict] = None
        self._spell_checker: Optional[SpellChecker] = None
        self._loaded: bool = False

        self._bi_encoder_name = (
            bi_encoder_model
            or getattr(self.config, "MODEL_NAME", "all-MiniLM-L6-v2")
        )
        self._reranker_model_name = (
            reranker_model or CrossEncoderReranker.DEFAULT_MODEL
        )

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def load(self) -> None:
        """Load all artefacts and models (idempotent)."""
        if self._loaded:
            return

        # Bi-encoder
        logger.info("Loading bi-encoder: '%s' ...", self._bi_encoder_name)
        self._bi_encoder = SentenceTransformer(self._bi_encoder_name)

        # FAISS index
        index_path = os.path.join(self.config.ARTIFACTS_DIR, "faiss_index.bin")
        if not os.path.exists(index_path):
            raise FileNotFoundError(
                f"FAISS index not found: {index_path}. Run train.py first."
            )
        self._index = faiss.read_index(index_path)
        logger.info("FAISS index loaded: %d vectors.", self._index.ntotal)

        # Passage map
        pm_path = os.path.join(self.config.ARTIFACTS_DIR, "passage_map.pkl")
        if not os.path.exists(pm_path):
            raise FileNotFoundError(
                f"Passage map not found: {pm_path}. Run train.py first."
            )
        import pickle
        with open(pm_path, "rb") as fh:
            self._passage_map = pickle.load(fh)
        logger.info("Passage map loaded: %d entries.", len(self._passage_map["passages"]))

        # Cross-encoder (lazy — only instantiated on first rerank call)
        if self.use_reranker:
            self._reranker = CrossEncoderReranker(self._reranker_model_name)

        # Spell checker
        self._spell_checker = SpellChecker()
        self._spell_checker.build_from_passages(self._passage_map["passages"])

        self._loaded = True
        logger.info("Searcher ready.")

    # ------------------------------------------------------------------
    # Query encoding
    # ------------------------------------------------------------------

    def _encode_query(self, query: str) -> np.ndarray:
        embedding = self._bi_encoder.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True,
        )
        return embedding.astype(np.float32)

    # ------------------------------------------------------------------
    # Search
    # ------------------------------------------------------------------

    def search(
        self,
        query: str,
        top_k: int = 10,
        rerank_top_n: int = 50,
        use_reranker: Optional[bool] = None,
    ) -> SearchResponse:
        """
        Perform semantic search for a natural language query.

        Args:
            query:         Query string.
            top_k:         Number of results to return.
            rerank_top_n:  Number of FAISS candidates to pass to the
                           cross-encoder (must be >= top_k).
            use_reranker:  Override instance setting for this call.

        Returns:
            SearchResponse with ranked results and metadata.
        """
        self.load()

        t0 = time.time()

        # "Did you mean?" — check before FAISS search
        did_you_mean = self._spell_checker.suggest(query) if self._spell_checker else None

        # Decide how many FAISS candidates to retrieve
        _use_reranker = use_reranker if use_reranker is not None else self.use_reranker
        n_candidates = max(top_k, rerank_top_n) if _use_reranker else top_k

        # Encode query
        q_emb = self._encode_query(query)

        # FAISS search
        scores, indices = self._index.search(q_emb, n_candidates)

        # Build initial result list
        n_passages = len(self._passage_map["passages"])
        candidates: List[SearchResult] = []
        for rank, (score, idx) in enumerate(zip(scores[0], indices[0]), start=1):
            if idx < 0 or idx >= n_passages:
                continue
            passage = self._passage_map["passages"][idx]
            candidates.append(
                SearchResult(
                    rank=rank,
                    passage_id=self._passage_map["ids"][idx],
                    passage=passage,
                    score=float(score),
                    snippet=_highlight_snippet(passage, query),
                    source="MS MARCO",
                )
            )

        # Cross-encoder re-ranking
        if _use_reranker and self._reranker and len(candidates) > 0:
            candidates = self._reranker.rerank(query, candidates)

        # Trim to top_k
        results = candidates[:top_k]

        latency_ms = (time.time() - t0) * 1000
        logger.info(
            "query='%s' top_k=%d latency=%.1fms reranker=%s",
            query[:60], top_k, latency_ms, _use_reranker,
        )

        return SearchResponse(
            query=query,
            results=results,
            latency_ms=round(latency_ms, 2),
            total_indexed=self._index.ntotal,
            did_you_mean=did_you_mean,
        )

    def search_batch(
        self,
        queries: List[str],
        top_k: int = 10,
        use_reranker: bool = False,   # reranker disabled by default for batches
    ) -> List[SearchResponse]:
        """
        Batch semantic search.  Re-ranking is disabled by default for batches
        because the cross-encoder scales O(N × K) per query.
        """
        self.load()

        t0 = time.time()
        q_embs = self._bi_encoder.encode(
            queries,
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=len(queries) > 10,
        ).astype(np.float32)

        scores_batch, indices_batch = self._index.search(q_embs, top_k)
        total_ms = (time.time() - t0) * 1000
        per_query_ms = total_ms / max(len(queries), 1)

        n_passages = len(self._passage_map["passages"])
        responses = []

        for q_idx, query in enumerate(queries):
            results: List[SearchResult] = []
            for rank, (score, idx) in enumerate(
                zip(scores_batch[q_idx], indices_batch[q_idx]), start=1
            ):
                if idx < 0 or idx >= n_passages:
                    continue
                passage = self._passage_map["passages"][idx]
                results.append(
                    SearchResult(
                        rank=rank,
                        passage_id=self._passage_map["ids"][idx],
                        passage=passage,
                        score=float(score),
                        snippet=_highlight_snippet(passage, query),
                        source="MS MARCO",
                    )
                )

            if use_reranker and self._reranker and results:
                results = self._reranker.rerank(query, results)

            responses.append(
                SearchResponse(
                    query=query,
                    results=results,
                    latency_ms=round(per_query_ms, 2),
                    total_indexed=self._index.ntotal,
                    did_you_mean=(
                        self._spell_checker.suggest(query) if self._spell_checker else None
                    ),
                )
            )

        logger.info(
            "Batch search: %d queries, total=%.1fms, per-query=%.1fms",
            len(queries), total_ms, per_query_ms,
        )
        return responses
